# Generated by Django 3.2.7 on 2021-12-06 05:31

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='thumbnails/')),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('setup_period', models.DateTimeField()),
                ('registration_period', models.DateTimeField()),
                ('running_period', models.DateTimeField()),
                ('grading_period', models.DateTimeField()),
                ('deactivated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Warning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500)),
                ('reason', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('deactivated', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warnings_revieved', to='accounts.profile')),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warnings_issued', to='course.semester')),
            ],
        ),
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500)),
                ('action_taken', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('by_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complains_made', to='accounts.profile')),
                ('for_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complains_revieved', to='accounts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='thumbnails/')),
                ('instructions', tinymce.models.HTMLField(blank=True, null=True)),
                ('quota', models.PositiveIntegerField(default=0)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('cancelled', models.BooleanField(default=False)),
                ('rating', models.FloatField(default=0)),
                ('completed_by', models.ManyToManyField(blank=True, null=True, related_name='completed_classes', to='accounts.Profile')),
                ('enrolled_by', models.ManyToManyField(blank=True, null=True, related_name='enrolled_classes', to='accounts.Profile')),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_classes', to='accounts.profile')),
            ],
        ),
    ]
