# Generated by Django 3.2.9 on 2021-11-25 13:43

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_useruniqueid_expired'),
        ('course', '0002_auto_20211125_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='enrolled_by',
            field=models.ManyToManyField(related_name='enrolled_classes', to='accounts.Profile'),
        ),
        migrations.AddField(
            model_name='class',
            name='instructions',
            field=tinymce.models.HTMLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='class',
            name='instructor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_classes', to='accounts.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='class',
            name='quota',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='semester',
            name='class_running_period',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='semester',
            name='class_setup_period',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='semester',
            name='grading_period',
            field=models.BooleanField(default=False),
        ),
    ]
