# Generated by Django 3.2.9 on 2021-12-05 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_grade_useruniqueid'),
        ('course', '0002_class_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500)),
                ('reason', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('deactivated', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warnings_revieved', to='accounts.profile')),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warnings_issued', to='course.semester')),
            ],
        ),
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500)),
                ('action_taken', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('by_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complains_made', to='accounts.profile')),
                ('for_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complains_revieved', to='accounts.profile')),
            ],
        ),
    ]
