# Generated by Django 3.2.9 on 2021-11-25 18:28

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_useruniqueid_expired'),
        ('course', '0003_auto_20211125_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='enrolled_by',
            field=models.ManyToManyField(blank=True, null=True, related_name='enrolled_classes', to='accounts.Profile'),
        ),
        migrations.AlterField(
            model_name='class',
            name='instructions',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_classes', to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='class',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
        migrations.CreateModel(
            name='Warning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warnings_revieved', to='accounts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500)),
                ('stars', models.PositiveIntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('by_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to='accounts.profile')),
                ('refferring_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='course.class')),
            ],
        ),
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('by_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complains_made', to='accounts.profile')),
                ('for_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complains_revieved', to='accounts.profile')),
            ],
        ),
    ]
