# Generated by Django 3.2.9 on 2021-11-26 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_auto_20211126_0347'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='deactivated',
            field=models.BooleanField(default=False),
        ),
    ]
