# Generated by Django 3.2.9 on 2021-11-26 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_auto_20211126_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='classes',
        ),
    ]
