# Generated by Django 3.2.9 on 2021-11-26 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_remove_semester_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='semester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='course.semester'),
            preserve_default=False,
        ),
    ]
