# Generated by Django 3.2.9 on 2021-11-27 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_auto_20211127_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
