# Generated by Django 3.2.9 on 2021-11-30 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0015_alter_class_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppingcart',
            old_name='course',
            new_name='courses',
        ),
    ]
