# Generated by Django 3.2.9 on 2021-11-30 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0016_rename_course_shoppingcart_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warning',
            name='semester',
            field=models.ForeignKey(blank=None, null=None, on_delete=django.db.models.deletion.CASCADE, related_name='warnings_issued', to='course.semester'),
        ),
    ]
