# Generated by Django 3.2.9 on 2021-11-30 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0017_alter_warning_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='warning',
            name='deactivated',
            field=models.BooleanField(default=False),
        ),
    ]
