# Generated by Django 3.2.9 on 2021-11-30 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0018_warning_deactivated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warning',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warnings_issued', to='course.semester'),
        ),
    ]
