# Generated by Django 3.2.9 on 2021-12-01 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0019_alter_warning_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabooWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=150)),
            ],
        ),
    ]
