# Generated by Django 3.2.9 on 2021-12-01 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20211127_1034'),
        ('course', '0021_classrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelOfHonor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expired', models.BooleanField(default=False)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.semester')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='honor_labels', to='accounts.profile')),
            ],
        ),
    ]
