# Generated by Django 3.2.7 on 2021-12-06 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='refferring_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_grades', to='course.class'),
        ),
        migrations.AddField(
            model_name='grade',
            name='to_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='accounts.profile'),
        ),
    ]
