# Generated by Django 3.2.9 on 2021-11-25 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20211125_0638'),
    ]

    operations = [
        migrations.AddField(
            model_name='useruniqueid',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
