# Generated by Django 3.2.9 on 2021-11-27 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_auto_20211127_0957'),
        ('accounts', '0009_useruniqueid_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='suspended',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GPA', models.FloatField(default=0.0)),
                ('by_instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_grades', to='accounts.profile')),
                ('refferring_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_grades', to='course.class')),
                ('to_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='accounts.profile')),
            ],
        ),
    ]
